//  This software code is made available "AS IS" without warranties of any
//  kind.  You may copy, display, modify and redistribute the software
//  code either by itself or as incorporated into your code; provided that
//  you do not remove any proprietary notices.  Your use of this software
//  code is at your own risk and you waive any claim against Amazon
//  Digital Services, Inc. or its affiliates with respect to your use of
//  this software code.
//
// (c) 2006 Three Rings Design, Inc.

package com.threerings.s3;


/** 
 * An exception that indicates a generic S3 error.
 */
public class S3Exception extends Exception
{
    // The following was autogenerated from the list of exceptions, copied from
    // http://docs.amazonwebservices.com/AmazonS3/2006-03-01/ErrorCodeList.html
    // cat errors | awk -F '\t' '{
    //     print "/**",$2"*/","\n" "public static class S3" substr($1, 1, length($1) - 1) "Exception extends S3Exception {\n}\n"
    // }'
    
    /** Access Denied  */ 
    public static class S3AccessDeniedException extends S3Exception {
    }

    /** There is a problem with your AWS account that prevents the operation from completing successfully. Please contact customer service at webservices@amazon.com. */ 
    public static class S3AccountProblemException extends S3Exception {
    }

    /** All access to this object has been disabled. */ 
    public static class S3AllAccessDisabledException extends S3Exception {
    }

    /** The e-mail address you provided is associated with more than one account. */ 
    public static class S3AmbiguousGrantByEmailAddressException extends S3Exception {
    }

    /** A conflicting conditional operation is currently in progress against this resource. Please try again. */ 
    public static class S3OperationAbortedException extends S3Exception {
    }

    /** The Content-MD5 you specified did not match what we received. */ 
    public static class S3BadDigestException extends S3Exception {
    }

    /** The named bucket you tried to create already exists. */ 
    public static class S3BucketAlreadyExistsException extends S3Exception {
    }

    /** The bucket you tried to delete is not empty. */ 
    public static class S3BucketNotEmptyException extends S3Exception {
    }

    /** This request does not support credentials. */ 
    public static class S3CredentialsNotSupportedException extends S3Exception {
    }

    /** Your proposed upload exceeds the maximum allowed object size. */ 
    public static class S3EntityTooLargeException extends S3Exception {
    }

    /** You did not provide the number of bytes specified by the Content-Length HTTP header */ 
    public static class S3IncompleteBodyException extends S3Exception {
    }

    /** We encountered an internal error. Please try again. */ 
    public static class S3InternalErrorException extends S3Exception {
    }

    /** The AWS Access Key Id you provided does not exist in our records. */ 
    public static class S3InvalidAccessKeyIdException extends S3Exception {
    }

    /** You must specify the Anonymous role. */ 
    public static class S3InvalidAddressingHeaderException extends S3Exception {
    }

    /** Invalid Argument */ 
    public static class S3InvalidArgumentException extends S3Exception {
    }

    /** The specified bucket is not valid. */ 
    public static class S3InvalidBucketNameException extends S3Exception {
    }

    /** The Content-MD5 you specified was an invalid. */ 
    public static class S3InvalidDigestException extends S3Exception {
    }

    /** The requested range is not satisfiable. */ 
    public static class S3InvalidRangeException extends S3Exception {
    }

    /** The provided security credentials are not valid. */ 
    public static class S3InvalidSecurityException extends S3Exception {
    }

    /** The SOAP request body is invalid. */ 
    public static class S3InvalidSOAPRequestException extends S3Exception {
    }

    /** The storage class you specified is not valid. */ 
    public static class S3InvalidStorageClassException extends S3Exception {
    }

    /** The target bucket for logging does not exist or is not owned by you. */ 
    public static class S3InvalidTargetBucketForLoggingException extends S3Exception {
    }

    /** Your key is too long. */ 
    public static class S3KeyTooLongException extends S3Exception {
    }

    /** Couldn't parse the specified URI. */ 
    public static class S3InvalidURIException extends S3Exception {
    }

    /** The XML you provided was not well-formed or did not validate against our published schema. */ 
    public static class S3MalformedACLErrorException extends S3Exception {
    }

    /** The XML you provided was not well-formed or did not validate against our published schema. */ 
    public static class S3MalformedXMLErrorException extends S3Exception {
    }

    /** Your request was too big. */ 
    public static class S3MaxMessageLengthExceededException extends S3Exception {
    }

    /** Your metadata headers exceed the maximum allowed metadata size. */ 
    public static class S3MetadataTooLargeException extends S3Exception {
    }

    /** The specified method is not allowed against this resource. */ 
    public static class S3MethodNotAllowedException extends S3Exception {
    }

    /** A SOAP attachment was expected, but none were found. */ 
    public static class S3MissingAttachmentException extends S3Exception {
    }

    /** You must provide the Content-Length HTTP header. */ 
    public static class S3MissingContentLengthException extends S3Exception {
    }

    /** The SOAP 1.1 request is missing a security element. */ 
    public static class S3MissingSecurityElementException extends S3Exception {
    }

    /** Your request was missing a required header. */ 
    public static class S3MissingSecurityHeaderException extends S3Exception {
    }

    /** There is no such thing as a logging status sub-resource for a key. */ 
    public static class S3NoLoggingStatusForKeyException extends S3Exception {
    }

    /** The specified bucket does not exist. */ 
    public static class S3NoSuchBucketException extends S3Exception {
    }

    /** The specified key does not exist. */ 
    public static class S3NoSuchKeyException extends S3Exception {
    }

    /** A header you provided implies functionality that is not implemented. */ 
    public static class S3NotImplementedException extends S3Exception {
    }

    /** Your account is not signed up for the S3 service. You must sign up before you can use S3. You can sign up at the following URL: http://aws.amazon.com/s3 */ 
    public static class S3NotSignedUpException extends S3Exception {
    }

    /** At least one of the pre-conditions you specified did not hold. */ 
    public static class S3PreconditionFailedException extends S3Exception {
    }

    /** Your socket connection to the server was not read from or written to within the timeout period. */ 
    public static class S3RequestTimeoutException extends S3Exception {
    }

    /** The difference between the request time and the server's time is too large. */ 
    public static class S3RequestTimeTooSkewedException extends S3Exception {
    }

    /** Requesting the torrent file of a bucket is not permitted. */ 
    public static class S3RequestTorrentOfBucketErrorException extends S3Exception {
    }

    /** The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the documentation under Authenticating REST Requests and Authenticating SOAP Requests for details. */ 
    public static class S3SignatureDoesNotMatchException extends S3Exception {
    }

    /** You have attempted to create more buckets than allowed. */ 
    public static class S3TooManyBucketsException extends S3Exception {
    }

    /** This request does not support content. */ 
    public static class S3UnexpectedContentException extends S3Exception {
    }

    /** The e-mail address you provided does not match any account on record. */ 
    public static class S3UnresolvableGrantByEmailAddressException extends S3Exception {
    }
}